version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
      - db # Add dependency on the new db service

  worker:
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
      - db # Add dependency on the new db service

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db: # New PostgreSQL service
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: webhook_db_test # Use the same DB name as in .env
      POSTGRES_USER: user # Use the same user as in .env
      POSTGRES_PASSWORD: password # Use the same password as in .env
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent data volume

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes: # Define the named volume for database persistence
  db_data:
